# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CollateralsApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CollateralsApp
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'


  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'CollateralsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CollateralsApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CollateralsApp-tvOS

  target 'CollateralsApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
