const Flags = {
    'United States': require('../assets/img/flags/USA.png'),
    Belgium: require('../assets/img/flags/Belgium.png'),
    Israel: require('../assets/img/flags/israel-flag-round-xs.png'),
    Sweden: require('../assets/img/flags/sweden-flag-round-xs.png'),
    Finland: require('../assets/img/flags/finland-flag-round-xs.png'),
    'Czech Republic': require('../assets/img/flags/czech-republic-flag-round-xs.png'),
    Hungary: require('../assets/img/flags/hungary-flag-round-xs.png'),
    Poland: require('../assets/img/flags/poland-flag-round-xs.png'),
    Italy: require('../assets/img/flags/italy-flag-round-xs.png'),
    France: require('../assets/img/flags/france-flag-round-xs.png'),
    Spain: require('../assets/img/flags/spain-flag-round-xs.png'),
    Portugal: require('../assets/img/flags/portugal-flag-round-xs.png'),
    Greece: require('../assets/img/flags/greece-flag-round-xs.png'),
    Egypt: require('../assets/img/flags/egypt-flag-round-xs.png'),
    Nigeria: require('../assets/img/flags/nigeria-flag-round-xs.png'),
    Ghana: require('../assets/img/flags/ghana-flag-round-xs.png'),
    'South Africa': require('../assets/img/flags/south-africa-flag-round-xs.png'),
    Switzerland: require('../assets/img/flags/switzerland-flag-round-xs.png'),
    Germany: require('../assets/img/flags/germany-flag-round-xs.png'),
    Canada: require('../assets/img/flags/canada-flag-round-xs.png'),
    Australia: require('../assets/img/flags/australia-flag-round-xs.png'),
    Fiji: require("../assets/img/flags/fiji-flag-round-xs.png"),
    'New Zealand': require('../assets/img/flags/new-zealand-flag-round-xs.png'),
    China: require('../assets/img/flags/china-flag-round-xs.png'),
    'Hong Kong': require('../assets/img/flags/china-flag-round-xs.png'),
    Philippines: require('../assets/img/flags/philippines-flag-round-xs.png'),
    Singapore: require('../assets/img/flags/singapore-flag-round-xs.png'),
    Vietnam: require('../assets/img/flags/vietnam-flag-round-xs.png'),
    Armenia: require('../assets/img/flags/armenia-flag-round-xs.png'),
    Georgia: require('../assets/img/flags/georgia-flag-round-xs.png'),
    Azerbaijan: require('../assets/img/flags/azerbaijan-flag-round-xs.png'),
    Tajikistan: require('../assets/img/flags/tajikistan-flag-round-xs.png'),
    Uzbekistan: require('../assets/img/flags/uzbekistan-flag-round-xs.png'),
    Kyrgyzstan: require('../assets/img/flags/kyrgyzstan-flag-round-xs.png'),
    India: require('../assets/img/flags/india-flag-round-xs.png'),
    Nepal: require('../assets/img/flags/nepal-flag-round-xs.png'),
    Bhutan: require('../assets/img/flags/bhutan-flag-round-xs.png'),
    Russia: require('../assets/img/flags/russia-flag-round-xs.png'),
    Kazakhstan: require('../assets/img/flags/kazakhstan-flag-round-xs.png'),
    Bulgaria: require('../assets/img/flags/bulgaria-flag-round-xs.png'),
    Croatia: require('../assets/img/flags/croatia-flag-round-xs.png'),
    Romania: require('../assets/img/flags/romania-flag-round-xs.png'),
    Netherlands: require('../assets/img/flags/netherlands-flag-round-xs.png'),
    Brazil: require('../assets/img/flags/brazil-flag-round-xs.png'),
    Uruguay: require('../assets/img/flags/uruguay-flag-round-xs.png'),
    Argentina: require('../assets/img/flags/argentina-flag-round-xs.png'),
    Chile: require('../assets/img/flags/chile-flag-round-xs.png'),
    Paraguay: require('../assets/img/flags/paraguay-flag-round-xs.png'),
    Mexico: require('../assets/img/flags/mexico-flag-round-xs.png'),
    Japan: require('../assets/img/flags/japan-flag-round-xs.png'),
    Mongolia: require('../assets/img/flags/mongolia-flag-round-xs.png'),
    Korea: require('../assets/img/flags/south-korea-flag-round-xs.png')
}

export default Flags;